#!/usr/bin/env php

<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application('Le Vadim Application',1.0);

$app->add(new SpeakCommand());

$app->run();