#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use Acme\NewCommand;
use Acme\RenderCommand;
use Acme\ShowCommand;
use Acme\AddCommand;
use Acme\CompleteCommand;
use Acme\DatabaseAdapter;
require 'vendor/autoload.php';

$app = new Application('Laracasts', 1.0);

$app->add(new NewCommand(new GuzzleHttp\Client));
$app->add(new RenderCommand());

try
{
    $pdo = new PDO('sqlite:db.sqlite');
    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    $pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
}
catch(Exception $e){
    echo $e;
    exit(1);
}

$dbAdapter = new DatabaseAdapter($pdo);
$app->add(new ShowCommand($dbAdapter));
$app->add(new AddCommand($dbAdapter));
$app->add(new CompleteCommand($dbAdapter));

$app->run();